DROP DATABASE IF EXISTS springdb;
CREATE DATABASE springdb CHARACTER SET UTF8;
USE springdb;
DROP TABLE IF EXISTS news;
CREATE TABLE news(
	nid 		INT 		AUTO_INCREMENT ,
	title 		VARCHAR(50) ,
	pubdate 	DATE ,
	content		TEXT ,
	CONSTRAINT 	pk_nid	PRIMARY KEY(nid)
);